// <auto-generated />
namespace SoftwareEngineeringP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10716_CreateConnection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10716_CreateConnection));
        
        string IMigrationMetadata.Id
        {
            get { return "201610071657093_10-7-16_CreateConnection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
